# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-seo-tag]

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: assets/css
  style: :nested

title:             "Gonzalo Oyanedel"
description:        "Personal site"
author:              "Gonzalo Oyanedel Vial"
